apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: velero
      interval: 5m
  releaseName: velero
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values: https://github.com/vmware-tanzu/helm-charts/blob/velero-8.1.0/charts/velero/values.yaml
  values:
    configuration:
      backupStorageLocation:
        - bucket: ${velero_backup_s3_bucket}
          provider: aws
      volumeSnapshotLocation:
        - config:
            region: ${velero_snapshot_aws_region}
          provider: aws
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      useSecret: true
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=${velero_aws_access_key_id}
          aws_secret_access_key=${velero_aws_secret_access_key}
