apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
  namespace: victoria-metrics
spec:
  interval: 120m
  url: https://victoriametrics.github.io/helm-charts/
